/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package imagestitching;

import boofcv.io.UtilIO;
import boofcv.io.image.UtilImageIO;
import boofcv.struct.image.GrayF32;

import java.awt.image.BufferedImage;

public class App {

    public static void main(String[] args) {
        BufferedImage imageA, imageB;
		imageA = UtilImageIO.loadImageNotNull(UtilIO.path("app/src/main/java/imagestitching/images/1.jpg"));
		imageB = UtilImageIO.loadImageNotNull(UtilIO.path("app/src/main/java/imagestitching/images/2.jpg"));
        Stitcher.stitch(imageA, imageB, GrayF32.class);
    }
}
